spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/lab8shop
spring.datasource.username='myuser'
spring.datasource.password='labos'

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect